config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :banks, :except => [:show, :destroy] do
      put :toggle_activation, :on => :member
    end
  end
  resources :payments, :only => :update
  get '/content/bank_transfer', :to => 'content#bank_transfer', :as => :bank_transfer_instructions
end

app/models/spree/bank.rb
module Spree
  class Bank < ActiveRecord::Base
    validates :name, :account_no , :presence => true
    validates_uniqueness_of :account_no , :scope => :name

    scope :active, -> { where(:active => true) }
  end
end

app/models/spree/payment_decorator.rb
Spree::Payment.class_eval do
  attr_accessor :validate_bank_details
  validates :bank_name, :account_no, :transaction_reference_no, :deposited_on, :presence => true, :if => :validate_bank_details

  scope :from_bank_transfer, -> { joins(:payment_method).where(:spree_payment_methods => { :type => 'Spree::PaymentMethod::BankTransfer' }) }

  def details_submitted?
    transaction_reference_no?
  end
end

app/models/spree/payment_method/bank_transfer.rb
module Spree
  class PaymentMethod::BankTransfer < PaymentMethod

    def actions
      %w{capture void}
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def capture(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def void(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def source_required?
      false
    end

    def credit(money, credit_card, response_code, options = {})
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end
  end

end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  has_many :payments, :through => :orders
end

app/controllers/spree/admin/banks_controller.rb
module Spree
  module Admin
    class BanksController < ResourceController
      def index
        @banks = Spree::Bank.page(params[:page])
      end

      def toggle_activation
        @success = @bank.toggle!(:active)
      end
    end
  end
end

app/controllers/spree/content_controller_decorator.rb
Spree::ContentController.class_eval do
  def bank_transfer
    render :layout => false
  end
end

app/controllers/spree/payments_controller.rb
module Spree
  class PaymentsController < Spree::StoreController
    before_filter :authenticate_spree_user!
    before_filter :find_payment

    def update
      payment_details = PaymentDetails.new(@payment, payment_params)
      if payment_details.save
        flash[:notice] = Spree.t(:payment_successfully_updated)
      else
        flash[:error] = payment_details.errors.to_sentence
      end
      redirect_to :back
    end

    def find_payment
      @payment = spree_current_user.payments.where(:number => params[:id]).first
      unless @payment
        flash[:error] = Spree.t(:payment_not_found)
        redirect_to :back
      end
    end

    private
      def payment_params
        params.require(:payment).permit(:deposited_on, :bank_name, :account_no, :transaction_reference_no)
      end
  end
end

app/helpers/spree/admin/banks_helper.rb
module Spree
  module Admin
    module BanksHelper

      def bank_status(bank)
        bank.active? ? Spree.t(:active) : Spree.t(:inactive)
      end

      def action_to_toggle_bank_status(bank)
        bank.active? ? Spree.t(:deactivate) : Spree.t(:activate)
      end

      def action_text_to_toggle_bank_status(bank)
        bank.active? ? 'remove-sign' : 'ok-sign'
      end

    end
  end
end

app/helpers/spree/admin/navigation_helper_decorator.rb
module Spree
  module Admin
    module NavigationHelper

      def link_to_with_icon(icon_name, text, url, options = {})
        options[:class] = (options[:class].to_s + " icon-link with-tip action-#{icon_name}").strip
        options[:class] += ' no-text' if options[:no_text]
        options[:title] = text if options[:no_text]
        text = options[:no_text] ? '' : raw("<span class='text'>#{text}</span>")
        text = text.gsub('\'', '"')
        options.delete(:no_text)
        if icon_name
          icon = content_tag(:span, '', class: "icon icon-#{icon_name}")
          text.insert(0, icon + ' ')
        end
        link_to(text.html_safe, url, options)
      end

    end
  end
end

app/views/spree/admin/banks/_form.html.erb
<div data-hook="admin_banks_form_fields">
  <div class="row">
    <%= f.field_container :name, :class => ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
      <%= f.error_message_on :name, :class => 'fullwidth title' %>
      <%= f.text_field :name, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :account_no, :class => ['form-group'] do %>
      <%= f.label :account_no, Spree.t(:account_no) %><span class="required">*</span><br />
      <%= f.text_field :account_no, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :additional_details, :class => ['form-group'] do %>
      <%= f.label :additional_details, Spree.t(:additional_details) %><br />
      <%= f.text_area :additional_details, :rows => 10, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :active, :class => ['checkbox'] do %>
      <%= f.label :active do %>
        <%= f.check_box :active %>
        <%= Spree.t(:active) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spree/admin/banks/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::Bank.model_name.human) %> / <%= @bank.name %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @bank } %>

<%= form_for @bank, :url => admin_bank_path(@bank) do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="actions">
      <%= button Spree.t('actions.update'), 'save' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/banks/index.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Bank) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_bank), new_object_url, :class => "btn-success", :icon => 'add', :id => 'admin_new_bank_link' %>
<% end %>

<% if @banks.any? %>

  <table class="table" id='listing_banks'>
    <thead>
      <tr data-hook="admin_banks_index_headers">
        <th><%= Spree.t(:bank_name) %></th>
        <th><%= Spree.t(:account_no) %></th>
        <th><%= Spree.t(:additional_details) %></th>
        <th><%= Spree.t(:status) %></th>
      </tr>
    </thead>
    <tbody>
      <% @banks.each do |bank|%>
        <tr id="<%= spree_dom_id bank %>" data-hook="admin_banks_index_rows">
          <td><%= bank.name %></td>
          <td><%= bank.account_no %></td>
          <td><%= bank.additional_details %></td>
          <td id='active-status-<%= bank.id %>'><%= bank_status(bank) %></td>
          <td data-hook="admin_banks_index_row_status" id='toggle-status-<%= bank.id %>' class="actions actions-2 text-right">
            <% action_class = bank.active ? "btn-danger" : "btn-success" %>
            <% btn_class = 'btn ' + action_class + ' btn-sm' %>
            <% status = bank.active ? "active" : "inactive" %>
            <% bank_id = 'bank-' + bank[:id].to_s %>
            <%= link_to_with_icon(action_text_to_toggle_bank_status(bank), action_to_toggle_bank_status(bank), toggle_activation_admin_bank_path(bank), {:class => btn_class, :id => bank_id, :rel => status, :remote => true, :method => :put}) %>
          </td>
          <td data-hook="admin_banks_index_row_actions" class="actions actions-2 text-right">            
            <%= link_to_edit(bank, :no_text => true) if can? :edit, bank %>
            <%= link_to_delete(bank, :no_text => true) if can? :delete, bank %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Bank)) %>,
    <%= link_to(Spree.t(:add_one), new_object_url) if can? :create, Spree::Bank %>!
  </div>
<% end %>

app/views/spree/admin/banks/new.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_bank) %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_banks_list), admin_banks_path, :class => 'btn btn-primary' %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @bank } %>

<%= form_for [:admin, @bank] do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/banks/toggle_activation.js.erb
<% if @success %>
  $('#active-status-<%= @bank.id %>').text('<%= bank_status(@bank) %>')
  <% action_class = @bank.active ? "btn-danger" : "btn-success" %>
  <% btn_class = "btn " + action_class + " btn-sm" %>
  <% status = @bank.active ? "active" : "inactive" %>
  <% bank_id = "bank-" + @bank[:id].to_s %>
  $('#toggle-status-<%= @bank.id %>').html('<%= link_to_with_icon(action_text_to_toggle_bank_status(@bank), action_to_toggle_bank_status(@bank), toggle_activation_admin_bank_path(@bank), {:class => btn_class, :id => bank_id, :rel => status, :remote => true, :method => :put}) %>')
<% else %>
  alert('<%= @bank.errors.full_messages.to_sentence %>')
<% end %>

app/views/spree/checkout/payment/_banktransfer.html.erb
<% if (banks = Spree::Bank.active).any? %>
  <table>
    <tr>
      <th><%= Spree.t(:bank_name) %></th>
      <th><%= Spree.t(:account_no) %></th>
      <th><%= Spree.t(:additional_details) %></th>
    </tr>
    <% banks.each do |bank| %>
      <tr>
        <td><%= bank.name %></td>
        <td><%= bank.account_no %></td>
        <td><%= bank.additional_details %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/spree/content/bank_transfer.html.erb
<h4>HOW BANK TRANSFER WORKS</h4>
<b>Steps:</b>
<ol>
  <li>Deposit order total in one of the below mentioned bank accounts. After this payment a payment reference number will be provided by the bank.
    <% if (banks = Spree::Bank.active).any? %>
      <div style="padding:20px 0">
      <table border="1" align='center' width="80%">
        <tr>
          <th><%= Spree.t(:bank_name) %></th>
          <th><%= Spree.t(:account_no) %></th>
          <th><%= Spree.t(:additional_details) %></th>
        </tr>
        <% banks.each do |bank| %>
          <tr>
            <td><center><%= bank.name %></center></td>
            <td><center><%= bank.account_no %></center></td>
            <td><center><%= bank.additional_details %></center></td>
          </tr>
        <% end %>
      </table>
      </div>
    <% end %>
  </li>
  <li>Enter this payment reference number on Order Details page by following steps:
    <ol style="padding:10px 0 0 20px" type='a'>
      <li>Go to "My Account" page.</li>
      <li>Select Order for which you want to provide details.</li>
      <li>Click on "Add Details" link visible in "Payment Information" column.</li>
      <li>Provide payment details and Submit.</li>
      <br><br>
      <%= image_tag 'payment_details.png' %>
    </ol>
  </li>
</ol>